# Generated by Django 4.2.7 on 2024-03-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utility_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='city',
            field=models.CharField(default='jnjn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='phone_number',
            field=models.CharField(default=9874564215, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='state',
            field=models.CharField(default=411041, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='zip_code',
            field=models.CharField(default=411041, max_length=10),
            preserve_default=False,
        ),
    ]
